name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
      - name: See fs
        run: ls -lAhR
      - name: Copy privkey
        run: composer install
      - name: Deploy to hoblox
        run: vendor/bin/behat --format-settings='{"paths":false}'
