name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Composer install
        run: composer install
      - name: Run behat
        run: vendor/bin/behat --format-settings='{"paths":false}'
